---
title: "TItanic_Logistic"
author: "Anna Wolford"
date: "2024-06-19"
output: html_document
---

## LOG BEFORE EDITS
```{r}
library(tidyverse)
library(tidymodels)
library(vroom)
library(rpart)
library(stacks)
library(embed)
library(ranger)
library(discrim)
library(naivebayes)
library(kernlab)
library(themis)

spaceTrain <- vroom("./train.csv")
spaceTest <- vroom("./test.csv")

spaceTrain <- spaceTrain %>%
  mutate(VIP = as.factor(VIP), CryoSleep = as.factor(CryoSleep), Transported =                                                                                     as.factor(Transported), 
         Destination=as.factor(Destination)) %>%
  separate(Cabin, into =c("CabinDeck", "CabinRmNumber", "CabinSide"), sep="/") %>% ## split Cabin based off of backslash
  select(-Name)

spaceTest <- spaceTest%>%
  mutate(VIP = as.factor(VIP), CryoSleep = as.factor(CryoSleep), 
         Destination=as.factor(Destination)) %>%
  separate(Cabin, into =c("CabinDeck", "CabinRmNumber", "CabinSide"), sep="/") %>% ## split Cabin based off of backslash
  select(-Name)

# view(spaceTrain)

## COME BACK TO THIS IDEA: potentially the $ spent NAs, fill in with a zero...? 

## ADDRESS NA
# sapply(spaceTrain, function(x) sum(is.na(x)))
## HomePlanet - most pop

```

```{r}
my_mod <- logistic_reg() %>%
  set_engine("glm")

my_recipe <- recipe(Transported~., data=spaceTrain) %>%
  update_role(PassengerId, new_role = "ID") %>%
  step_lencode_mixed(all_nominal_predictors(), outcome = vars(Transported)) %>%
  step_impute_mean(all_numeric_predictors()) %>%
  ## step_impute_knn(all_numeric_predictors()) %>%
  step_mutate(totalSpent = RoomService+FoodCourt+ShoppingMall+Spa+VRDeck)

prepped_rec <- prep(my_recipe)
baked_rec <- bake(prepped_rec, spaceTrain)

```

```{r}
space_workflow <- workflow() %>%
  add_recipe(my_recipe) %>%
  add_model(my_mod) %>%
  fit(data=spaceTrain)

space_predictions <- predict(space_workflow,
                              new_data=spaceTest,
                              type="class") %>%
  bind_cols(., spaceTest) %>%
  select(PassengerId, .pred_class) %>%
  rename(Transported=.pred_class) %>%
  mutate(Transported = ifelse(Transported == TRUE, "True", "False"))

vroom_write(x=space_predictions, file="./SPACE_log.csv", delim=",")


```


## Penalized Logistic Regression

```{r}
library(tidyverse)
library(tidymodels)
library(vroom)
library(rpart)
library(stacks)
library(embed)
library(ranger)
library(discrim)
library(naivebayes)
library(kernlab)
library(themis)

spaceTrain <- vroom("./train.csv")
spaceTest <- vroom("./test.csv")

spaceTrain <- spaceTrain %>%
  mutate(VIP = as.factor(VIP), CryoSleep = as.factor(CryoSleep), Transported =                                                                                     as.factor(Transported), 
         Destination=as.factor(Destination)) %>%
  separate(Cabin, into =c("CabinDeck", "CabinRmNumber", "CabinSide"), sep="/") %>% ## split Cabin based off of backslash
  select(-Name)

spaceTest <- spaceTest%>%
  mutate(VIP = as.factor(VIP), CryoSleep = as.factor(CryoSleep), 
         Destination=as.factor(Destination)) %>%
  separate(Cabin, into =c("CabinDeck", "CabinRmNumber", "CabinSide"), sep="/") %>% ## split Cabin based off of backslash
  select(-Name)

my_mod <- logistic_reg(mixture=.5, penalty=10) %>%
  set_engine("glmnet")

my_recipe <- recipe(Transported~., data=spaceTrain) %>%
  update_role(PassengerId, new_role = "ID") %>%
  step_lencode_mixed(all_nominal_predictors(), outcome = vars(Transported)) %>%
  step_impute_mean(all_numeric_predictors()) %>%
  ## step_impute_knn(all_numeric_predictors()) %>%
  step_mutate(totalSpent = RoomService+FoodCourt+ShoppingMall+Spa+VRDeck)

prepped_rec <- prep(my_recipe)
baked_rec <- bake(prepped_rec, spaceTrain)

```

```{r}
space_workflow <- workflow() %>%
  add_recipe(my_recipe) %>%
  add_model(my_mod) %>%
  fit(data=spaceTrain)


space_predictions <- predict(space_workflow,
                              new_data=spaceTest,
                              type="class") %>%
  bind_cols(., spaceTest) %>%
  select(PassengerId, .pred_class) %>%
  rename(Transported=.pred_class) %>%
  mutate(Transported = ifelse(Transported == TRUE, "True", "False"))

vroom_write(x=space_predictions, file="./SPACE_pen_log_dont_quit.csv", delim=",")


```

